name: 'End Portal'
description: 'GitHub Actions workflow to automate build'
author: 'TaciturnCoder'

jobs:
  # GitHub Actions workflow to automate build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to default branch
        uses: actions/checkout@v3
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Run post-build scripts
        run: |
          # currently none
          echo "Printing structure of ./_site"
          ls -lar "./_site"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
